version: '2'
services:
  nginx:
    build:
      context: ./cookbooks
      dockerfile: $PWD/Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - nova
      - pulsar
    command: [nginx-debug, '-g', 'daemon off;']
  db:
    image: mysql:5.7
    volumes:
      - ./tmp/db:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - "3307:3306"
  redis:
    image: redis
    ports:
      - "6379:6379"
  nova:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    volumes:
      - .:/app/nova:cached
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "db"
      REDIS_HOST: "redis"
    depends_on:
      - db
  sidekiq:
    build: .
    command: bundle exec sidekiq
    tty: true
    stdin_open: true
    volumes:
      - .:/app/nova:cached
    environment:
      DATABASE_HOST: "db"
      REDIS_HOST: "redis"
    depends_on:
      - db
      - redis
  pulsar:
    build:
      context: ../pulsar
    command: /app/pulsar
    ports:
      - "3001:3001"
    environment:
      PULSAR_BIND_ADDR: "0.0.0.0:3001"
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
