FROM nginx:mainline

RUN mkdir /etc/nginx/sites-enabled

COPY nginx/files/etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/files/etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default

RUN sed -i -e 's/server 127.0.0.1:3000;$/server nova:3000;/g' -e 's/server 127.0.0.1:3001;$/server pulsar:3001;/g' /etc/nginx/sites-enabled/default
